<a href="https://colab.research.google.com/github/varunk04/Deep_learning_with_Tensorflow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors:

In [ ]:
# Import tensorflow:
import tensorflow as tf
print(tf.__version__)

In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(79)
scalar

In [ ]:
# check the number of dimensions of a tensor:

scalar.ndim

In [ ]:
# Create a vector:

vector = tf.constant([79,79])
vector

In [ ]:
# check the dimension of vector:
vector.ndim

In [ ]:
# Create a matrix;

matrix = tf.constant([
    [79,79],
    [79,79]
])
matrix

In [ ]:
matrix.ndim

In [ ]:
# Create another matix:

An_matrix = tf.constant([
    [79.0,79.0],
    [79.0,79.0],
    [79.0,79.0]
],dtype=tf.float16)

An_matrix

In [ ]:
An_matrix.ndim

In [ ]:
# Creating a tensor:

tensor = tf.constant([
    [
        [79,79,79],
        [79,79,79]
    ],
    [
        [4,4,4],
        [4,4,4,]  
    ],
    [
        [10,10,10],
        [10,10,10]
    ]
])

tensor

In [ ]:
tensor.ndim

* Scalar is a single number
* Vector is a number with direction
* matrix is a 2-dimensional array of numbers
* Tensor is a collection of matrix(Which means it is a multidimensional array

**TENSOR** dimensions can be interprested as follows:
tesnor.ndim = (M,R,C)
M is number of matrices
R is number of rows in the matrix
c is number of columns in the matrix

Foe example:
(3,2,2) diemension vector tells that there are total of 3, 2*2 dimesion matrices in the tensor. 

### Creating tensor with 'tf.variable'

In [ ]:
# Creating same tensor with tf.variable:

changeable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([1,2])

changeable_tensor,unchangeable_tensor

In [ ]:
changeable_tensor[0] = 4
changeable_tensor

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

In tensorflow we can create two type of tensors:

1. unchangeable type by usinmf tf.constant()
2. changeable tensor by using tf.Variable ()

### Creating random tensors:

Random tensor are the tensors made from  a arbritary random numbers

In [ ]:
# Creating a random tensor:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape = (3,3))

random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape = (3,3,3))
random1,random2

### Shuffle the order of elements in tensor:

In [ ]:
# Shuffling a tensor (usefull when we want to shuffle the data)

not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6],
                            [7,8]])
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled)

# Everytime you run this function it will shuffle the tensor.

In [ ]:
# setting seed will help us reproduce it.

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

### Other ways to make tensors:


In [ ]:
tf.ones([10,7])

In [ ]:
tf.zeros(shape=(10,7))

### converting numpy array to tensors:

* main purpose of conversion is unliike tensors, numpy arrays cannot run on GPUs.

In [ ]:
import numpy as np

numpy_a = np.arange(1,26, dtype= np.int32).reshape(5,5)
numpy_a

In [ ]:
tensor_a = tf.constant(numpy_a)
tensor_a

In [ ]:
# We can re shape the numpy array as we wish

tensor_a = tf.constant(numpy_a, shape = (1,5,5))
tensor_a

### Getting more information about the tensors:

when dealing with tensors, one should be aware of these attributes:

* shape
* Axis or dimension
* Rank
* size

In [ ]:
# creating a multi rank tensor:

tensor = tf.ones(shape= [2,3,4,5,])
tensor

In [ ]:
# Indexing:
tensor[0]

In [ ]:
tensor.shape, tensor.ndim, tf.size(tensor)

In [ ]:
# Get various attributes of tensor:

def get_attributes(input_tensor):
  ''' This function takes tensor as input and print the various attributes 
  of the tensor '''
  
  print('Datatype of every elements :',input_tensor.dtype)
  print('Number of dimensions :', input_tensor.ndim)
  print('Shape of the tensor :', input_tensor.shape)
  print('Number of elements in the tensor :', tf.size(input_tensor).numpy())


In [ ]:
get_attributes(tensor)

### Indexing tensors:

In [ ]:
tensor

In [ ]:
tensor[:2,:2,:2,:2]

In [ ]:
# get the first element from each dimension from each index except for the final element:

tensor[:1,:1,:,:1]

In [ ]:
# Create a rak 2 tensor (2 Dimension)
rank2_tensor = tf.constant([
    [1,2],
    [3,4]
])

In [ ]:
get_attributes(rank2_tensor)

In [ ]:
# get last item of each row:
rank2_tensor[:,-1]

In [ ]:
# Add in extra dimension to rank 2 tensor:

rank3_tensor = rank2_tensor[...,tf.newaxis]
rank3_tensor

In [ ]:
# Alternative to tf.newaxis:

tf.expand_dims(rank2_tensor, axis = -1) # expand at the end

In [ ]:
tf.expand_dims(rank2_tensor, axis = 0) # expand at first

### manipulating tensors (tensor Operations):

**Basic Operations**

In [ ]:
# Adding value to tensor:

tensor = tf.constant([
    [1,2],
    [3,4]
])

tensor + 10

In [ ]:
# Multiplications:
tensor * 10

In [ ]:
# Sustraction:

tensor - 10

In [ ]:
# We can use the tensprflow built in function too:

tf.multiply(tensor , 10)

**Matrix Multiplication :**

* It is most common operation done, usual multiplication is carried out element wise.
* But there are other ways to multiply the matrices.

In [ ]:
# Multiplying tensor:
print(tensor)
tf.matmul(tensor, tensor)

In [ ]:
# There is a short hand for matmul:

tensor @ tensor

### Changing the datatype of the tensor:

In [ ]:
a = tf.constant([1,2,3])
a.dtype

tf.int32

In [ ]:
b = tf.constant([1.,2.,3.,4.])
b.dtype

tf.float32

In [ ]:
# Changing the int32 to int16 dtype:

c = tf.cast(a, dtype = tf.int16)
c.dtype

tf.int16

In [ ]:
# Changing the float32 to float16 dtype:

d = tf.cast(b, dtype = tf.float16)
d.dtype

tf.float16

### Aggregating Tensors:

Aggregating tensors = condensing the, from multiple values to a smaller values.

In [ ]:
# getting the absolute value:
# Converting negative vlaues to positive.

tensor = tf.constant([10,20,-30,-40])
tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 10,  20, -30, -40], dtype=int32)>

In [ ]:
tf.abs(tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

* Get maximum
* Get Minimum
* Get mean
* Get sum

In [ ]:
# Creating a random-tensor:

rand_tensor = tf.constant(np.random.randint(0,100, size = 50))
rand_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([13, 92, 41, 29, 41, 45, 33, 75, 75, 53, 44, 89, 69, 82, 54, 69, 57,
       23, 97, 62, 28, 87, 61, 81, 39, 19, 84,  4,  0, 23, 86, 86, 19, 85,
       18, 83,  4, 67, 85, 93, 33, 33, 16,  6, 96,  1,  4, 11, 57, 31])>

In [ ]:
# getting tensor_ atrributes:

get_attributes(rand_tensor)

Datatype of every elements : <dtype: 'int64'>
Number of dimensions : 1
Shape of the tensor : (50,)
Number of elements in the tensor : 50


In [ ]:
# Find minimum:

tf.reduce_min(rand_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find Maximum:

tf.reduce_max(rand_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# Finding mean:

tf.reduce_mean(rand_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
# sum:

tf.reduce_sum(rand_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2483>

In [ ]:
# varinace
import tensorflow_probability as tfp

tfp.stats.variance(rand_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=937>

In [ ]:
# STD:
# standard deviance is in math module and it takes floar32 as input, so we have to cast the dtype:
tf.math.reduce_std(tf.cast(rand_tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.618694>

* Getting postional Arguments:

In [ ]:
# Create a new tensor:
tf.random.set_seed(42)
A = tf.random.uniform(shape = [50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the postional maximum:

tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our larggest value of the tensor:

A[tf.argmax(A)] == tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the postional minimum:

tf.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Indexing the minimum value:

A[tf.argmin(A)] == tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing the tensor(removing all the single dimensions):

In [ ]:
# Lets create the tensor:

x = tf.constant(tf.random.uniform(shape = [50]), shape= (1,1,1,1,50))
x

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
           0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
           0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
           0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
           0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
           0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
           0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
           0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
           0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
           0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669]]]]],
      dtype=float32)>

In [ ]:
# Get the attributes:

get_attributes(x)

Datatype of every elements : <dtype: 'float32'>
Number of dimensions : 5
Shape of the tensor : (1, 1, 1, 1, 50)
Number of elements in the tensor : 50


In [ ]:
# Squeezing:
# squeeze removes all the Dimensional of 1 from the shape of the tensor
x_squeeze  = tf.squeeze(x)

x_squeeze, get_attributes(x_squeeze)

Datatype of every elements : <dtype: 'float32'>
Number of dimensions : 1
Shape of the tensor : (50,)
Number of elements in the tensor : 50


(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
        0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
        0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
        0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
        0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
        0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
        0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
        0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
        0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
        0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669],
       dtype=float32)>,
 None)

### One-hot encoding the tensors:

* It is a way of numrical encode the categorical data.


In [ ]:
# Create a list of indices:

some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth = len(some_list))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root:

In [ ]:
# Squaring a tensor:

y = tf.constant([10,20,30,40,50])
tf.square(y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 100,  400,  900, 1600, 2500], dtype=int32)>

In [ ]:
# Sqrt:

tf.sqrt(tf.cast(y, dtype = tf.float32))

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([3.1622777, 4.472136 , 5.477226 , 6.3245554, 7.071068 ],
      dtype=float32)>

In [ ]:
# Log:

tf.math.log(tf.cast(y, dtype = tf.float32))

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([2.3025851, 2.9957323, 3.4011974, 3.6888795, 3.912023 ],
      dtype=float32)>

### Tensor and NumPy:

In [ ]:
# Create a tensor directly from numpy array:

N = tf.constant(np.array([1,2,3,4]))
N

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
# Convert tensor to numpy array:

np.array(N), type(np.array(N))

(array([1, 2, 3, 4]), numpy.ndarray)